version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27020:27017

  web:
    build: .
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_PATH=mongodb://mongo:27017
      - DATABASE_NAME=ekom
      - COLLECTION_NAME=forms
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=pass
    depends_on:
      - mongo
